name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          docker buildx create --use
          docker buildx build --push --tag 065538148774.dkr.ecr.ap-southeast-1.amazonaws.com/dashboard:latest .
        env:
          ECR_REPO_URI: ${{ secrets.ECR_BACKEND }}

      - name: SSH into EC2 and pull and run Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 065538148774.dkr.ecr.ap-southeast-1.amazonaws.com
            sudo docker pull 065538148774.dkr.ecr.ap-southeast-1.amazonaws.com/dashboard:latest
            sudo docker stop backend
            sudo docker rm backend
            sudo docker run --net=backend -p 4000:4000 -d --name backend 065538148774.dkr.ecr.ap-southeast-1.amazonaws.com/dashboard:latest
            # Additional commands or configuration as needed
